name: Deploy static site to GitHub Pages

# Trigger deployment on pushes to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository content
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy to GitHub Pages using peaceiris/actions-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # GitHub Token to authorize the action
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Directory to publish (root of the repo)
          publish_dir: ./
          # Branch to publish to (default: gh-pages)
          publish_branch: gh-pages
          # Keep .gitignore and GitHub workflow files out of the published branch
          exclude_assets: |
            .gitignore
            .github/**
